<?php
namespace app\components\web;

use app\models\Cart;
use lajax\translatemanager\helpers\Language;

class Controller extends \yii\web\Controller
{

    public function init()
    {
        parent::init();
    }

    public function beforeAction($action)
    {
        \Yii::$app->cart->init();
        
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}
