<?php

namespace app\models;

use Yii;
use yii\db\Expression;

/**
 * This is the model class for table "keresendo_log".
 *
 * @property integer $id
 * @property string $keresoszo
 * @property integer $talalat
 * @property string $datum
 * @property string $ip
 * @property string $browser
 */
class KeresendoLog extends \app\components\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'keresendo_log';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['keresoszo', 'talalat', 'datum', 'ip', 'browser'], 'required'],
            [['talalat'], 'integer'],
            [['datum'], 'safe'],
            [['keresoszo'], 'string', 'max' => 128],
            [['ip'], 'string', 'max' => 16],
            [['browser'], 'string', 'max' => 256],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'keresoszo' => 'Keresoszo',
            'talalat' => 'Talalat',
            'datum' => 'Datum',
            'ip' => 'Ip',
            'browser' => 'Browser',
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord)
            $this->datum = new Expression('NOW()');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
